# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crews.Region'),
            preserve_default=False,
        ),
    ]
