# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0002_employee_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.AddField(
            model_name='crew',
            name='eletrician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eletrician', to='crews.Employee'),
        ),
        migrations.AddField(
            model_name='crew',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Region'),
        ),
        migrations.AddField(
            model_name='crew',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='crews.Employee'),
        ),
    ]
