# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0003_auto_20160929_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_off', models.DateTimeField(verbose_name=b'dia de folga')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Employee')),
            ],
        ),
    ]
