# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0004_dayoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('plate', models.CharField(max_length=8)),
                ('revision', models.DateTimeField(verbose_name=b'ultima revisao')),
            ],
        ),
    ]
