# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='km_last_revision',
            field=models.CharField(default=b'0', max_length=10),
        ),
        migrations.AddField(
            model_name='crew',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crews.Car'),
            preserve_default=False,
        ),
    ]
