# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0007_historicalcar_historicalcrew_historicaldayoff_historicalemployee_historicalregion_historicalrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcar',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcrew',
            name='car',
        ),
        migrations.RemoveField(
            model_name='historicalcrew',
            name='eletrician',
        ),
        migrations.RemoveField(
            model_name='historicalcrew',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcrew',
            name='region',
        ),
        migrations.RemoveField(
            model_name='historicalcrew',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='historicaldayoff',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='historicaldayoff',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='historicalregion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCar',
        ),
        migrations.DeleteModel(
            name='HistoricalCrew',
        ),
        migrations.DeleteModel(
            name='HistoricalDayOff',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
        migrations.DeleteModel(
            name='HistoricalRegion',
        ),
        migrations.DeleteModel(
            name='HistoricalRole',
        ),
    ]
