# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0009_employee_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Viatura'},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'verbose_name': 'Equipe'},
        ),
        migrations.AlterModelOptions(
            name='dayoff',
            options={'verbose_name': 'Folga'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('name',), 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Regional', 'verbose_name_plural': 'Regionais'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Cargo'},
        ),
    ]
