# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crews', '0009_employee_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('meter', models.CharField(blank=True, max_length=11)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('revenue', models.CharField(blank=True, max_length=1)),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crews.Region')),
            ],
        ),
    ]
