# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour', models.DateTimeField(verbose_name='timestamp')),
                ('channel_1_value', models.FloatField()),
                ('channel_2_value', models.FloatField()),
                ('channel_3_value', models.FloatField()),
                ('channel_1_qty', models.CharField(max_length=3)),
                ('channel_2_qty', models.CharField(max_length=3)),
                ('channel_3_qty', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='installation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='history',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer'),
        ),
    ]
