# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20160929_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='region',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='crews.Region'),
        ),
    ]
