# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20160929_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.CharField(max_length=20)),
                ('date_hour', models.DateTimeField(verbose_name='read hour')),
                ('reader', models.CharField(max_length=6)),
                ('serial', models.CharField(max_length=8)),
                ('model', models.CharField(max_length=4)),
                ('version', models.CharField(max_length=4)),
                ('constant1', models.CharField(max_length=13)),
                ('constant2', models.CharField(max_length=13)),
                ('constant3', models.CharField(max_length=13)),
                ('channel_1_qty', models.CharField(max_length=3)),
                ('channel_2_qty', models.CharField(max_length=3)),
                ('channel_3_qty', models.CharField(max_length=3)),
                ('last_integration', models.DateTimeField(verbose_name='ultima integracao')),
                ('last_bill', models.DateTimeField(verbose_name='ultima fatura')),
                ('penultimate_bill', models.DateTimeField(verbose_name='penultima fatura')),
            ],
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Consumidor', 'verbose_name_plural': 'Consumidores'},
        ),
    ]
