# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0005_energyfault'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=41)),
                ('mm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Mm')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='MeterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(verbose_name='valido desde')),
                ('until', models.DateTimeField(verbose_name='valido ate')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Meter')),
            ],
        ),
    ]
