# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0008_auto_20161011_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('quantity', models.CharField(max_length=5)),
            ],
        ),
    ]
