# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0009_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mm',
            name='channel_1_qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel1', to='mm.Quantity'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='channel_2_qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel2', to='mm.Quantity'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='channel_3_qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel3', to='mm.Quantity'),
        ),
    ]
