# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0010_auto_20161011_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyfault',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
