# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0012_auto_20161011_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateTimeField(verbose_name='feriado')),
                ('mm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Mm')),
            ],
        ),
    ]
