# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0015_auto_20161011_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='channel_1_qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel1_history', to='mm.Quantity'),
        ),
        migrations.AlterField(
            model_name='history',
            name='channel_2_qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel2_history', to='mm.Quantity'),
        ),
        migrations.AlterField(
            model_name='history',
            name='channel_3_qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel3_history', to='mm.Quantity'),
        ),
    ]
