# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0016_auto_20161012_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='mm',
        ),
        migrations.AddField(
            model_name='change',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Meter'),
        ),
    ]
