# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0017_auto_20161020_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
