# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0019_auto_20161020_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='description',
        ),
    ]
