# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0020_remove_change_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='observation',
            field=models.CharField(blank=True, max_length=86, null=True),
        ),
    ]
