# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0021_change_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mm',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
