# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mm', '0004_auto_20160930_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(blank=True, max_length=15)),
                ('code', models.CharField(blank=True, max_length=3)),
                ('date_time_executed', models.DateTimeField(verbose_name='competencia da baixa')),
                ('date_time_load', models.DateTimeField(verbose_name='data da baixa')),
                ('observation', models.TextField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
            ],
        ),
    ]
