# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models

import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='date_time_competence',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016,1,1), verbose_name='competencia da baixa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_time_executed',
            field=models.DateTimeField(verbose_name='data da execucao'),
        ),
    ]
