# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20160930_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name': 'Inspecao', 'verbose_name_plural': 'Inspecoes'},
        ),
    ]
