# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0016_auto_20161012_1040'),
        ('analysis', '0003_auto_20161002_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.DateField(verbose_name='referencia')),
                ('revenue_days', models.IntegerField()),
                ('reader_msg', models.CharField(blank=True, max_length=3, null=True)),
                ('read', models.FloatField()),
                ('billed', models.FloatField()),
                ('init_cycle', models.DateField(verbose_name='init_cycle')),
                ('end_cycle', models.DateField(verbose_name='end_cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=24)),
                ('code', models.CharField(max_length=4)),
                ('unity', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Register'),
        ),
        migrations.AddField(
            model_name='billing',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer'),
        ),
    ]
