# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0020_remove_change_description'),
        ('analysis', '0005_auto_20161018_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour_begin', models.DateTimeField(verbose_name='date_hour_begin')),
                ('date_hour_end', models.DateTimeField(verbose_name='date_hour_end')),
                ('value1', models.FloatField()),
                ('value2', models.FloatField()),
                ('value3', models.FloatField()),
                ('analyzed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Justified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('observation', models.TextField()),
                ('expires', models.BooleanField()),
                ('date_hour', models.DateTimeField(verbose_name='date_hour_justified')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Alarm')),
            ],
        ),
        migrations.AddField(
            model_name='alarm',
            name='alarm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AlarmType'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer'),
        ),
    ]
