# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20161021_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='reference',
            field=models.DateField(blank=True, null=True, verbose_name='alarm_reference'),
        ),
    ]
