# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0021_change_observation'),
        ('analysis', '0007_alarm_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAlteracoesMedidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(verbose_name='data_alteracao')),
                ('leitor', models.CharField(max_length=6)),
                ('code', models.CharField(max_length=2)),
                ('observacao', models.CharField(max_length=86)),
                ('justificado', models.BooleanField()),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('expira', models.BooleanField()),
                ('data_hora', models.DateTimeField(blank=True, null=True, verbose_name='date_hour_justified')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
            ],
        ),
        migrations.RemoveField(
            model_name='justified',
            name='alarm',
        ),
        migrations.DeleteModel(
            name='Justified',
        ),
    ]
