# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0021_change_observation'),
        ('analysis', '0008_auto_20161026_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioCorrenteZerada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='inicio corrente zerada')),
                ('fim', models.DateTimeField(verbose_name='fim corrente zerada')),
                ('ia', models.FloatField()),
                ('ib', models.FloatField()),
                ('ic', models.FloatField()),
                ('justificado', models.BooleanField()),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('expira', models.BooleanField()),
                ('data_hora', models.DateTimeField(blank=True, null=True, verbose_name='date_hour_justified')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioTensaoZerada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='inicio tensao zerada')),
                ('fim', models.DateTimeField(verbose_name='fim tensao zerada')),
                ('va', models.FloatField()),
                ('vb', models.FloatField()),
                ('vc', models.FloatField()),
                ('justificado', models.BooleanField()),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('expira', models.BooleanField()),
                ('data_hora', models.DateTimeField(blank=True, null=True, verbose_name='date_hour_justified')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
            ],
        ),
    ]
