# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0021_change_observation'),
        ('analysis', '0009_relatoriocorrentezerada_relatoriotensaozerada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioMMVersusConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_faturado', models.FloatField()),
                ('consumo_mm', models.FloatField()),
                ('tipo_comparacao', models.CharField(max_length=4)),
                ('constante', models.CharField(max_length=13)),
                ('justificado', models.BooleanField()),
                ('mes_referencia', models.DateField(verbose_name='mes_referencia')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('expira', models.BooleanField()),
                ('data_hora', models.DateTimeField(blank=True, null=True, verbose_name='date_hour_justified')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Meter')),
            ],
        ),
    ]
