# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_relatoriommversusconsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriommversusconsumo',
            name='recorrencias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
