# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0021_change_observation'),
        ('analysis', '0012_remove_relatoriommversusconsumo_recorrencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriommversusconsumo',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Mm'),
        ),
    ]
