# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_remove_relatoriommversusconsumo_constante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriommversusconsumo',
            name='expira',
        ),
    ]
