# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_relatorioquedadeconsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioquedadeconsumo',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
    ]
