# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_relatorioquedadeconsumo_justificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriocorrentezerada',
            name='expira',
        ),
        migrations.RemoveField(
            model_name='relatoriotensaozerada',
            name='expira',
        ),
        migrations.AddField(
            model_name='relatoriotensaozerada',
            name='data_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data_expira'),
        ),
    ]
