# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0024_auto_20170105_1558'),
        ('crews', '0011_carhistory'),
        ('analysis', '0019_auto_20161120_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Crew')),
            ],
        ),
    ]
