# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0024_auto_20170105_1558'),
        ('analysis', '0020_protocolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Company')),
            ],
        ),
    ]
