# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0025_auto_20170304_1245'),
        ('analysis', '0021_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioalteracoesmedidor',
            name='company',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Company'),
        ),
        migrations.AddField(
            model_name='relatoriocorrentezerada',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Company'),
        ),
        migrations.AddField(
            model_name='relatoriommversusconsumo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Company'),
        ),
        migrations.AddField(
            model_name='relatorioquedadeconsumo',
            name='company',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Company'),
        ),
        migrations.AddField(
            model_name='relatoriotensaozerada',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Company'),
        ),
    ]
