# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0025_auto_20170304_1245'),
        ('analysis', '0022_auto_20170313_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudeNaoIncrementada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_fraude', models.DateTimeField(verbose_name='mes_fraude')),
                ('code_fraude', models.CharField(max_length=4)),
                ('faturamento_anterior', models.FloatField()),
                ('faturamento_posterior', models.FloatField()),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_expira', models.DateTimeField(blank=True, null=True, verbose_name='data_expira')),
                ('data_hora', models.DateTimeField(blank=True, null=True, verbose_name='date_hour_justified')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm.Company')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
            ],
        ),
    ]
