# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_fraudenaoincrementada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FraudeNaoIncrementada',
            new_name='RelatorioFraudeNaoIncrementada',
        ),
    ]
