# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_auto_20170405_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofraudenaoincrementada',
            name='justificado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
