# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crews', '0011_carhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.DateTimeField(verbose_name='envio')),
                ('instalacao', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('familia_codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('data_realizacao', models.DateField(verbose_name='data_realizacao')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Region')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producao',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.TipoServico'),
        ),
    ]
