# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-29 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0025_auto_20170304_1245'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlvosAbertos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(blank=True, max_length=12, null=True)),
                ('data_geracao', models.DateField(verbose_name='data_geracao')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Consumer')),
            ],
        ),
    ]
