# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0011_carhistory'),
        ('producao', '0002_alvosabertos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlvosDespachados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despacho', models.DateField(verbose_name='data_despacho')),
                ('alvo_aberto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.AlvosAbertos')),
                ('inspetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Employee')),
            ],
        ),
    ]
