# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_alvosdespachados'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='data_devolucao'),
        ),
    ]
