# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo'},
        ),
    ]
